import Butter from '../../assets/butter.png'
import Strawberry from '../../assets/strawberry.png'
import Eggs from '../../assets/eggs.png'
import Cabbage from '../../assets/cabbage.png'
import Eggplant from '../../assets/eggplant.png'
import Shrimp from '../../assets/shrimp.png'
import Kiwi from '../../assets/kiwi.png'
import Capsicum from '../../assets/capsicum.png'
import Broccoli from '../../assets/broccoli.png'
import Yogurt from '../../assets/yogurt.png'
import Beef from '../../assets/beef.png'
import ChickenBreast from '../../assets/chicken-breast.png'
import Kale from '../../assets/kale.png'
import Cheese from '../../assets/cheese.png'
import CondensedMilk from '../../assets/condensed-milk.png'
import Salmon from '../../assets/salmon.png'
import Banana from '../../assets/banana.png'
import Milk from '../../assets/milk.png'
import Pineapple from '../../assets/pineapple.png'
import Tofu from '../../assets/tofu.png'
import Tilapia from '../../assets/tilapia.png'
import SliceCheese from '../../assets/slice-cheese.png'
import RicottaCheese from '../../assets/ricotta-cheese.png'
import Grapes from '../../assets/grapes.png'
import Lettuce from '../../assets/lettuce.png'

const ProductList = [
  {
    id: 1,
    name: "Strawberry",
    price: 3.0,
    oldPrice: 4.8,
    category: "Fruits",
    onSale: true,
    newArrival: true,
    image: Strawberry,
  },
  {
    id: 2,
    name: "Butter",
    price: 3.5,
    oldPrice: 4.0,
    category: "Dairy",
    onSale: true,
    newArrival: false,
    image: Butter,
  },
  {
    id: 3,
    name: "Eggs",
    price: 2.05,
    oldPrice: 3.0,
    category: "Dairy",
    onSale: false,
    newArrival: false,
    image: Eggs,
  },
  {
    id: 4,
    name: "Cabbage",
    price: 3.0,
    oldPrice: 4.0,
    category: "Vegetables",
    onSale: true,
    newArrival: true,
    image: Cabbage,
  },
  {
    id: 5,
    name: "Eggplant",
    price: 4.0,
    oldPrice: 5.0,
    category: "Vegetables",
    onSale: true,
    newArrival: true,
    image: Eggplant,
  },
  {
    id: 6,
    name: "Shrimp",
    price: 3.5,
    oldPrice: 4.0,
    category: "Sea Foods",
    onSale: false,
    newArrival: false,
    image: Shrimp,
  },
  {
    id: 7,
    name: "Kiwi",
    price: 2.05,
    oldPrice: 3.0,
    category: "Fruits",
    onSale: true,
    newArrival: false,
    image: Kiwi,
  },
  {
    id: 8,
    name: "Green Capsicum",
    price: 4.0,
    oldPrice: 5.0,
    category: "Vegetables",
    onSale: false,
    newArrival: false,
    image: Capsicum,
  },
  {
    id: 9,
    name: "Broccoli",
    price: 2.0,
    oldPrice: 3.0,
    category: "Vegetables",
    onSale: true,
    newArrival: true,
    image: Broccoli,
  },
  {
    id: 10,
    name: "Yogurt",
    price: 3.0,
    oldPrice: 4.0,
    category: "Dairy",
    onSale: false,
    newArrival: true,
    image: Yogurt,
  },
  {
    id: 11,
    name: "Beef",
    price: 8.0,
    oldPrice: 9.0,
    category: "Meat",
    onSale: true,
    newArrival: false,
    image: Beef,
  },
  {
    id: 12,
    name: "Chicken Breast",
    price: 7.0,
    oldPrice: 8.0,
    category: "Meat",
    onSale: false,
    newArrival: false,
    image: ChickenBreast,
  },
  {
    id: 13,
    name: "Kale Leaves",
    price: 3.0,
    oldPrice: 4.0,
    category: "Vegetables",
    onSale: true,
    newArrival: false,
    image: Kale,
  },
  {
    id: 14,
    name: "Mozzarella Cheese",
    price: 7.0,
    oldPrice: 8.0,
    category: "Dairy",
    onSale: false,
    newArrival: true,
    image: Cheese,
  },
  {
    id: 15,
    name: "Condensed Milk",
    price: 5.0,
    oldPrice: 8.0,
    category: "Dairy",
    onSale: false,
    newArrival: false,
    image: CondensedMilk,
  },
  {
    id: 16,
    name: "Salmon Filet ",
    price: 4.0,
    oldPrice: 5.0,
    category: "Sea Foods",
    onSale: false,
    newArrival: true,
    image: Salmon,
  },
  {
    id: 17,
    name: "Banana ",
    price: 2.0,
    oldPrice: 4.0,
    category: "Fruits",
    onSale: true,
    newArrival: false,
    image: Banana,
  },
  {
    id: 18,
    name: "Milk Bottle (3)",
    price: 8.0,
    oldPrice: 9.0,
    category: "Dairy",
    onSale: false,
    newArrival: false,
    image: Milk,
  },
  {
    id: 19,
    name: "PineApple",
    price: 5.0,
    oldPrice: 6.0,
    category: "Fruits",
    onSale: true,
    newArrival: false,
    image: Pineapple,
  },
  {
    id: 20,
    name: "Tofu Cubes",
    price: 4.0,
    oldPrice: 5.0,
    category: "Dairy",
    onSale: false,
    newArrival: false,
    image: Tofu,
  },
  {
    id: 21,
    name: "Tilapia Fish",
    price: 3.0,
    oldPrice: 5.0,
    category: "Sea Foods",
    onSale: true,
    newArrival: false,
    image: Tilapia,
  },
  {
    id: 22,
    name: "Slice Cheese",
    price: 5.0,
    oldPrice: 6.0,
    category: "Dairy",
    onSale: false,
    newArrival: true,
    image: SliceCheese,
  },
  {
    id: 23,
    name: "Ricotta Cheese",
    price: 7.0,
    oldPrice: 8.0,
    category: "Dairy",
    onSale: true,
    newArrival: true,
    image: RicottaCheese,
  },
  {
    id: 24,
    name: "Grapes",
    price: 3.0,
    oldPrice: 4.0,
    category: "Fruits",
    onSale: false,
    newArrival: false,
    image: Grapes,
  },
  {
    id: 25,
    name: "Lettuce Leaf",
    price: 3.0,
    oldPrice: 4.0,
    category: "Vegetables",
    onSale: true,
    newArrival: false,
    image: Lettuce,
  },
];

export default ProductList
